# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "/about"
  weight = 1

[[main]]
  name = "Blog"
  url = "/post"
  weight = 2

[[main]]
  name = "Projects"
  url = "/projects"
  weight = 3

[[main]]
  name = "Publications"
  url = "/publication"
  weight = 4

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 6
  
[[main]]
  name = "Honor"
  url = "certificates/"
  identifier = "certificate"
  weight = 7
  
[[main]]
  name = "Awards"
  url = "certificates/#award"
  parent = "certificate"
  weight = 1

[[main]]
  name = "Python Certificates"
  url = "certificates/#python"
  parent = "certificate"
  weight = 2

[[main]]
  name = "R Certificates"
  url = "certificates/#r"
  parent = "certificate"
  weight = 3

[[main]]
  name = "Other Programming Languages"
  url = "certificates/#other"
  parent = "certificate"
  weight = 4
  
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "Resume"    
  url = "files/resume.pdf"
  weight = 70
